import CoreGraphics
import Foundation

// シミュレータで UIKit のドラッグ & ドロップを動かして記録した、行き先の提案の列と実際に隙間が動いた位置の列。
// 提案は `dropSessionDidUpdate` に渡った値 (nil は項目の無い所) と指の位置、隙間はレイアウトに届いた位置。
// 同じ提案と位置が続く呼び出しは 3 回までに縮めている。
struct KsReorderGapRecording {
    struct Update {
        let proposal: IndexPath?
        let location: CGPoint
    }

    let name: String
    let source: IndexPath
    // 持ち上げた項目と同じセクションにだけ置ける判定を使ったか。
    let sameSectionOnly: Bool
    let updates: [Update]
    let gaps: [IndexPath]

    static let all: [KsReorderGapRecording] = [list26, list26SameGroup, grid26, list18SameGroup, grid18]

    // iOS 26.5・list・グループ 5 件ずつ・グループ 3 の 2 番目を持ち上げて上下へ動かす
    static let list26 = KsReorderGapRecording(
        name: "list26",
        source: IndexPath(item: 1, section: 2),
        sameSectionOnly: false,
        updates: [
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 111, y: 646)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 122, y: 606)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 122, y: 606)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 122, y: 606)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 122, y: 606)),
            Update(proposal: nil, location: CGPoint(x: 93, y: 566)),
            Update(proposal: nil, location: CGPoint(x: 93, y: 566)),
            Update(proposal: nil, location: CGPoint(x: 93, y: 566)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 128, y: 526)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 96, y: 513)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 96, y: 513)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 96, y: 513)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 75, y: 488)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 75, y: 488)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 75, y: 488)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 500)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 500)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 500)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 110, y: 500)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 110, y: 500)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 110, y: 500)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 110, y: 500)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 106, y: 460)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 105, y: 432)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 96, y: 420)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 96, y: 420)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 96, y: 420)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 77, y: 445)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 77, y: 445)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 77, y: 445)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 77, y: 445)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 105, y: 433)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 433)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 433)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 433)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 76, y: 408)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 76, y: 408)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 110, y: 433)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 110, y: 433)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 110, y: 433)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 76, y: 421)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 76, y: 421)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 76, y: 421)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 74, y: 461)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 109, y: 421)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 109, y: 421)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 113, y: 433)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 113, y: 433)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 113, y: 433)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 119, y: 445)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 107, y: 457)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 107, y: 457)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 107, y: 457)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 89, y: 445)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 89, y: 445)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 89, y: 445)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 114, y: 420)),
            Update(proposal: IndexPath(item: 1, section: 1), location: CGPoint(x: 106, y: 380)),
            Update(proposal: IndexPath(item: 1, section: 1), location: CGPoint(x: 101, y: 405)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 74, y: 470)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 96, y: 495)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 79, y: 483)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 72, y: 495)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 72, y: 495)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 72, y: 495)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 72, y: 495)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 118, y: 455)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 120, y: 480)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 120, y: 480)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 120, y: 480)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 114, y: 468)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 114, y: 468)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 114, y: 468)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 101, y: 493)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 74, y: 505)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 74, y: 505)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 74, y: 505)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 100, y: 493)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 100, y: 493)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 74, y: 533)),
            Update(proposal: nil, location: CGPoint(x: 114, y: 573)),
            Update(proposal: nil, location: CGPoint(x: 114, y: 573)),
            Update(proposal: nil, location: CGPoint(x: 114, y: 573)),
            Update(proposal: nil, location: CGPoint(x: 106, y: 613)),
            Update(proposal: nil, location: CGPoint(x: 106, y: 613)),
            Update(proposal: nil, location: CGPoint(x: 106, y: 613)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 88, y: 625)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 88, y: 625)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 88, y: 625)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 126, y: 637)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 71, y: 625)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 71, y: 625)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 71, y: 625)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 80, y: 613)),
            Update(proposal: nil, location: CGPoint(x: 101, y: 573)),
            Update(proposal: nil, location: CGPoint(x: 101, y: 573)),
            Update(proposal: nil, location: CGPoint(x: 119, y: 548)),
            Update(proposal: nil, location: CGPoint(x: 119, y: 548)),
            Update(proposal: nil, location: CGPoint(x: 119, y: 548)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 117, y: 523)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 95, y: 535)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 80, y: 495)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 507)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 507)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 122, y: 482)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 122, y: 482)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 122, y: 482)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 122, y: 482)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 87, y: 507)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 87, y: 507)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 87, y: 507)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 87, y: 507)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 92, y: 519)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 92, y: 519)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 92, y: 519)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 84, y: 531)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 112, y: 466)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 112, y: 466)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 112, y: 466)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 112, y: 466)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 101, y: 426)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 86, y: 401)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 86, y: 401)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 86, y: 401)),
            Update(proposal: IndexPath(item: 1, section: 1), location: CGPoint(x: 79, y: 361)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 79, y: 361)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 79, y: 361)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 79, y: 361)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 93, y: 386)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 93, y: 386)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 93, y: 386)),
            Update(proposal: IndexPath(item: 1, section: 1), location: CGPoint(x: 90, y: 411)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 90, y: 411)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 90, y: 411)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 90, y: 411)),
            Update(proposal: IndexPath(item: 2, section: 1), location: CGPoint(x: 124, y: 451)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 124, y: 451)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 124, y: 451)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 124, y: 451)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 111, y: 476)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 111, y: 476)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 111, y: 476)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 73, y: 516)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 516)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 516)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 516)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 121, y: 556)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 95, y: 568)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 95, y: 568)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 95, y: 568)),
            Update(proposal: nil, location: CGPoint(x: 76, y: 580)),
            Update(proposal: nil, location: CGPoint(x: 76, y: 580)),
            Update(proposal: nil, location: CGPoint(x: 76, y: 580)),
            Update(proposal: nil, location: CGPoint(x: 100, y: 580)),
        ],
        gaps: [IndexPath(item: 0, section: 2), IndexPath(item: 4, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 4, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 2, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 2, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 2, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 2, section: 1), IndexPath(item: 1, section: 1), IndexPath(item: 2, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 4, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 4, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 4, section: 1), IndexPath(item: 5, section: 1), IndexPath(item: 0, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 0, section: 2), IndexPath(item: 4, section: 1), IndexPath(item: 5, section: 1), IndexPath(item: 4, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 4, section: 1), IndexPath(item: 5, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 2, section: 1), IndexPath(item: 1, section: 1), IndexPath(item: 2, section: 1), IndexPath(item: 3, section: 1), IndexPath(item: 4, section: 1), IndexPath(item: 5, section: 1)]
    )

    // iOS 26.5・list・同じグループにだけ置ける判定
    static let list26SameGroup = KsReorderGapRecording(
        name: "list26SameGroup",
        source: IndexPath(item: 1, section: 2),
        sameSectionOnly: true,
        updates: [
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 111, y: 646)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 122, y: 606)),
            Update(proposal: nil, location: CGPoint(x: 93, y: 566)),
            Update(proposal: nil, location: CGPoint(x: 93, y: 566)),
            Update(proposal: nil, location: CGPoint(x: 93, y: 566)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 128, y: 526)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 128, y: 526)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 128, y: 526)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 72, y: 501)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 72, y: 501)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 72, y: 501)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 96, y: 513)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 96, y: 513)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 96, y: 513)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 75, y: 488)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 75, y: 488)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 75, y: 488)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 73, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 73, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 73, y: 500)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 110, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 110, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 110, y: 500)),
            Update(proposal: nil, location: CGPoint(x: 106, y: 560)),
            Update(proposal: nil, location: CGPoint(x: 106, y: 560)),
            Update(proposal: nil, location: CGPoint(x: 106, y: 560)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 600)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 600)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 600)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 105, y: 640)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 96, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 96, y: 690)),
            Update(proposal: IndexPath(item: 3, section: 2), location: CGPoint(x: 77, y: 730)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 77, y: 730)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 77, y: 730)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 77, y: 730)),
            Update(proposal: IndexPath(item: 3, section: 2), location: CGPoint(x: 105, y: 700)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 700)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 700)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 700)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 76, y: 650)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 110, y: 610)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 110, y: 610)),
            Update(proposal: nil, location: CGPoint(x: 76, y: 570)),
            Update(proposal: nil, location: CGPoint(x: 76, y: 570)),
            Update(proposal: nil, location: CGPoint(x: 76, y: 570)),
            Update(proposal: nil, location: CGPoint(x: 74, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 74, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 74, y: 530)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 109, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 109, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 109, y: 500)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 113, y: 470)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 113, y: 470)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 113, y: 470)),
            Update(proposal: nil, location: CGPoint(x: 119, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 119, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 119, y: 530)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 107, y: 590)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 107, y: 590)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 107, y: 590)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 89, y: 640)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 114, y: 700)),
            Update(proposal: IndexPath(item: 4, section: 2), location: CGPoint(x: 98, y: 760)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 96, y: 650)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 79, y: 600)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 79, y: 600)),
            Update(proposal: nil, location: CGPoint(x: 72, y: 560)),
            Update(proposal: nil, location: CGPoint(x: 72, y: 560)),
            Update(proposal: nil, location: CGPoint(x: 72, y: 560)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 118, y: 520)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 118, y: 520)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 118, y: 520)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 120, y: 580)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 120, y: 580)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 120, y: 580)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 114, y: 640)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 114, y: 640)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 114, y: 640)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 114, y: 640)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 101, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 101, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 101, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 101, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 100, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 100, y: 690)),
        ],
        gaps: [IndexPath(item: 0, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 2, section: 2), IndexPath(item: 3, section: 2), IndexPath(item: 2, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 0, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 2, section: 2), IndexPath(item: 4, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 0, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 2, section: 2)]
    )

    // iOS 26.5・2 列グリッド・グループ 3 の 3 番目を持ち上げて動かす
    static let grid26 = KsReorderGapRecording(
        name: "grid26",
        source: IndexPath(item: 2, section: 2),
        sameSectionOnly: false,
        updates: [
            Update(proposal: IndexPath(item: 4, section: 2), location: CGPoint(x: 89, y: 520)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 565)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 565)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 565)),
            Update(proposal: nil, location: CGPoint(x: 89, y: 543)),
            Update(proposal: nil, location: CGPoint(x: 89, y: 543)),
            Update(proposal: nil, location: CGPoint(x: 89, y: 543)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 588)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 588)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 588)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 44, y: 610)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 44, y: 610)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 44, y: 610)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 44, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 565)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 565)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 565)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 30, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 620)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 120, y: 575)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 553)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 553)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 553)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 508)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 508)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 508)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 530)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 575)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 575)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 575)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 75, y: 597)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 597)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 597)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 597)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 619)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 619)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 619)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 30, y: 575)),
            Update(proposal: nil, location: CGPoint(x: 30, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 30, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 30, y: 529)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 551)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 551)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 551)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 30, y: 596)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 75, y: 573)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 551)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 551)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 551)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 529)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 210, y: 551)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 506)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 506)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 506)),
            Update(proposal: IndexPath(item: 4, section: 2), location: CGPoint(x: 300, y: 484)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 552)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 552)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 552)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 507)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 507)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 507)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 300, y: 485)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 300, y: 485)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 300, y: 485)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 300, y: 440)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 165, y: 440)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 440)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 395)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 395)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 395)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 210, y: 418)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 210, y: 418)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 210, y: 418)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 210, y: 418)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 374)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 374)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 374)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 352)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 352)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 352)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 330)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 330)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 330)),
        ],
        gaps: [IndexPath(item: 4, section: 2), IndexPath(item: 0, section: 3), IndexPath(item: 2, section: 3), IndexPath(item: 0, section: 3), IndexPath(item: 2, section: 3), IndexPath(item: 0, section: 3), IndexPath(item: 2, section: 3), IndexPath(item: 0, section: 3), IndexPath(item: 1, section: 3), IndexPath(item: 3, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 0, section: 2), IndexPath(item: 1, section: 2)]
    )

    // iOS 18.6・list・同じグループにだけ置ける判定
    static let list18SameGroup = KsReorderGapRecording(
        name: "list18SameGroup",
        source: IndexPath(item: 1, section: 2),
        sameSectionOnly: true,
        updates: [
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 111, y: 646)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 111, y: 646)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 111, y: 646)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 122, y: 606)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 122, y: 606)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 122, y: 606)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 122, y: 606)),
            Update(proposal: nil, location: CGPoint(x: 93, y: 566)),
            Update(proposal: nil, location: CGPoint(x: 93, y: 566)),
            Update(proposal: nil, location: CGPoint(x: 93, y: 566)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 128, y: 526)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 128, y: 526)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 128, y: 526)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 72, y: 501)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 72, y: 501)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 72, y: 501)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 96, y: 513)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 96, y: 513)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 96, y: 513)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 75, y: 488)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 75, y: 488)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 75, y: 488)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 73, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 73, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 73, y: 500)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 130, y: 460)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 110, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 110, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 110, y: 500)),
            Update(proposal: nil, location: CGPoint(x: 106, y: 560)),
            Update(proposal: nil, location: CGPoint(x: 106, y: 560)),
            Update(proposal: nil, location: CGPoint(x: 106, y: 560)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 600)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 600)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 73, y: 600)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 105, y: 640)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 96, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 96, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 96, y: 690)),
            Update(proposal: IndexPath(item: 3, section: 2), location: CGPoint(x: 77, y: 730)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 77, y: 730)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 77, y: 730)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 77, y: 730)),
            Update(proposal: IndexPath(item: 3, section: 2), location: CGPoint(x: 105, y: 700)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 700)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 700)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 105, y: 700)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 76, y: 650)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 110, y: 610)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 110, y: 610)),
            Update(proposal: nil, location: CGPoint(x: 76, y: 570)),
            Update(proposal: nil, location: CGPoint(x: 76, y: 570)),
            Update(proposal: nil, location: CGPoint(x: 76, y: 570)),
            Update(proposal: nil, location: CGPoint(x: 74, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 74, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 74, y: 530)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 109, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 109, y: 500)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 109, y: 500)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 113, y: 470)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 113, y: 470)),
            Update(proposal: IndexPath(item: 3, section: 1), location: CGPoint(x: 113, y: 470)),
            Update(proposal: nil, location: CGPoint(x: 119, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 119, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 119, y: 530)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 107, y: 590)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 107, y: 590)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 107, y: 590)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 89, y: 640)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 114, y: 700)),
            Update(proposal: IndexPath(item: 4, section: 2), location: CGPoint(x: 106, y: 760)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 98, y: 760)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 98, y: 760)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 98, y: 760)),
            Update(proposal: IndexPath(item: 3, section: 2), location: CGPoint(x: 74, y: 700)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 96, y: 650)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 79, y: 600)),
            Update(proposal: nil, location: CGPoint(x: 72, y: 560)),
            Update(proposal: nil, location: CGPoint(x: 72, y: 560)),
            Update(proposal: nil, location: CGPoint(x: 72, y: 560)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 118, y: 520)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 118, y: 520)),
            Update(proposal: IndexPath(item: 4, section: 1), location: CGPoint(x: 118, y: 520)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 120, y: 580)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 120, y: 580)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 120, y: 580)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 114, y: 640)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 114, y: 640)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 114, y: 640)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 114, y: 640)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 101, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 101, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 101, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 101, y: 690)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 100, y: 690)),
        ],
        gaps: [IndexPath(item: 0, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 2, section: 2), IndexPath(item: 3, section: 2), IndexPath(item: 2, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 0, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 2, section: 2), IndexPath(item: 4, section: 2), IndexPath(item: 2, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 0, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 2, section: 2)]
    )

    // iOS 18.6・2 列グリッド
    static let grid18 = KsReorderGapRecording(
        name: "grid18",
        source: IndexPath(item: 2, section: 2),
        sameSectionOnly: false,
        updates: [
            Update(proposal: IndexPath(item: 4, section: 2), location: CGPoint(x: 89, y: 520)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 565)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 565)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 565)),
            Update(proposal: nil, location: CGPoint(x: 89, y: 543)),
            Update(proposal: nil, location: CGPoint(x: 89, y: 543)),
            Update(proposal: nil, location: CGPoint(x: 89, y: 543)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 588)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 588)),
            Update(proposal: nil, location: CGPoint(x: 134, y: 588)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 44, y: 610)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 44, y: 610)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 44, y: 610)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 44, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 565)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 565)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 565)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 30, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 610)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 620)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 620)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 120, y: 575)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 553)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 553)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 553)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 508)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 508)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 508)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 530)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 530)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 575)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 575)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 575)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 75, y: 597)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 597)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 597)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 597)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 619)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 619)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 30, y: 619)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 30, y: 575)),
            Update(proposal: nil, location: CGPoint(x: 30, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 30, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 30, y: 529)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 551)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 551)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 75, y: 551)),
            Update(proposal: IndexPath(item: 1, section: 3), location: CGPoint(x: 30, y: 596)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 75, y: 573)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 551)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 551)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 551)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 529)),
            Update(proposal: IndexPath(item: 0, section: 3), location: CGPoint(x: 210, y: 551)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 506)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 506)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 506)),
            Update(proposal: IndexPath(item: 4, section: 2), location: CGPoint(x: 300, y: 484)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 529)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 552)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 552)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 552)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 507)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 507)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 507)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 300, y: 485)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 300, y: 485)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 300, y: 485)),
            Update(proposal: IndexPath(item: 1, section: 2), location: CGPoint(x: 300, y: 440)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 165, y: 440)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 440)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 440)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 165, y: 440)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 395)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 395)),
            Update(proposal: nil, location: CGPoint(x: 120, y: 395)),
            Update(proposal: IndexPath(item: 0, section: 2), location: CGPoint(x: 210, y: 418)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 210, y: 418)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 210, y: 418)),
            Update(proposal: IndexPath(item: 2, section: 2), location: CGPoint(x: 210, y: 418)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 374)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 374)),
            Update(proposal: nil, location: CGPoint(x: 300, y: 374)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 352)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 352)),
            Update(proposal: nil, location: CGPoint(x: 255, y: 352)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 330)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 330)),
            Update(proposal: nil, location: CGPoint(x: 345, y: 330)),
        ],
        gaps: [IndexPath(item: 4, section: 2), IndexPath(item: 0, section: 3), IndexPath(item: 2, section: 3), IndexPath(item: 0, section: 3), IndexPath(item: 2, section: 3), IndexPath(item: 0, section: 3), IndexPath(item: 2, section: 3), IndexPath(item: 0, section: 3), IndexPath(item: 1, section: 3), IndexPath(item: 3, section: 2), IndexPath(item: 1, section: 2), IndexPath(item: 0, section: 2), IndexPath(item: 1, section: 2)]
    )
}
